#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
set -e # abort on errors
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf $ET_SRCDIR
#clear out status file since re-making
rm -f status

cd $SW_BLDDIR

tar -xzf /sw/sources/namd/${ET_VER}/${ET_SRCDIR}.tar.gz

cd $ET_SRCDIR

simfactory/bin/sim setup-silent --machine bluewaters
cat >>simfactory/bin/defs.local.ini <<EOF
[bluewaters]
sourcebasedir = $SW_BLDDIR
allocation = fyy
EOF
simfactory/bin/sim build --machine bluewaters --thornlist manifest/einsteintoolkit.org

############################### if this far, return 0
exit 0
