#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
set -e # abort on errors
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf $ET_SRCDIR
#clear out status file since re-making
rm -f status

cd $SW_BLDDIR

# GNU tar exists with 2 for actual errors and 1 for "file changed while
# reading" yet 2 is treated specially by swtools
tar -xzf /sw/sources/EinsteinToolkit/${ET_VER}/${ET_SRCDIR}.tar.gz || exit 1

cd $ET_SRCDIR

simfactory/bin/sim setup-silent --machine bluewaters
cat >>simfactory/etc/defs.local.ini <<EOF
[bluewaters]
sourcebasedir = $SW_BLDDIR
basedir = $SW_WORKDIR
allocation = fyy
submitpattern=(\d+[.]jyc)
EOF
# even when the build itself fails we still want to compute the number of error
# messages to plot them in Jenkins
#simfactory/bin/sim build --machine bluewaters --thornlist manifest/einsteintoolkit.th 2>&1 | tee make.log
simfactory/bin/sim build --machine bluewaters --thornlist /dev/null 2>&1 | tee make.log

# HACK: make it possible to execute some commands once run finishes
# the nicer way is of course to define out own SubmitScript or at least to make
# one *before* building the configuration but that is actually harder to do
mv configs/sim/SubmitScript configs/sim/SubmitScript.orig
gawk '/^[^#]/&&!wrotetrap { 
  print "trap \"rm @SW_BLDDIR@/.running\" EXIT"
  wrotetrap=1
}
{print}' configs/sim/SubmitScript.orig > configs/sim/SubmitScript
cat <<EOF >>configs/sim/SubmitScript
if grep --silent 'Number failed *-> 0' @RUNDIR@/TEST/sim/summary.log ; then
  echo verified >@SW_BLDDIR@/status
else
  echo unverified >@SW_BLDDIR@/status
if 
"
EOF

############################### if this far, return 0
exit 0
